### ISSUE TITLE
runClient not working for 1.16 project with mixins

### ISSUE THREAD

**Issue by embeddedt** [architectury/architectury-loom-runtime#1]
I am using Architectury Loom 1.0 with a Forge 1.16 project. The mod builds and works fine in a modpack, but when trying to use `runClient`, I get the following crash:

```
[11:31:09] [Render thread/INFO] (STDOUT) [net.minecraft.Bootstrap:println:123]: ---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 1/3/23, 11:31 AM
Description: Initializing game

org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[mixin-patched-0.8.4.8.jar:?] {}
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-patched-0.8.4.8.jar:?] {}
	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-patched-0.8.4.8.jar:?] {}
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-patched-0.8.4.8.jar:?] {}
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154) ~[modlauncher-8.1.3.jar:8.1.3+8.1.3+main-8.1.x.c94d18ec] {}
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.1.3.jar:?] {re:classloading}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.1.3.jar:?] {re:classloading}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient.java:474) ~[forge-1.16.5-36.2.28-minecraft-project-@-merged-named.jar:?] {re:mixin,pl:accesstransformer:B,pl:unprotect:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:rubidium.mixins.json:features.gui.fast_fps_pie.MixinMinecraftClient,pl:mixin:APP:rubidium.mixins.json:features.options.MixinMinecraftClient,pl:mixin:A,pl:unprotect:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:149) ~[forge-1.16.5-36.2.28-minecraft-project-@-merged-named.jar:?] {re:classloading,pl:unprotect:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.userdev.FMLUserdevClientLaunchProvider.lambda$launchService$0(FMLUserdevClientLaunchProvider.java:52) ~[forge-1.16.5-36.2.28-minecraft-project-@-merged-named.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {}
	at net.minecraftforge.userdev.LaunchTesting.main(LaunchTesting.java:108) [forge-1.16.5-36.2.28-minecraft-project-@-merged-named.jar:?] {}
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) [dev-launch-injector-0.2.1+build.8.jar:?] {}
Caused by: org.spongepowered.asm.mixin.throwables.MixinError: Error initialising injector metaclass [class org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo] for annotation Lorg/spongepowered/asm/mixin/injection/Inject;
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:156) ~[mixin-patched-0.8.4.8.jar:?] {}
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708) ~[mixin-patched-0.8.4.8.jar:?] {}
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1311) ~[mixin-patched-0.8.4.8.jar:?] {}
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1042) ~[mixin-patched-0.8.4.8.jar:?] {}
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393) ~[mixin-patched-0.8.4.8.jar:?] {}
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[mixin-patched-0.8.4.8.jar:?] {}
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383) ~[mixin-patched-0.8.4.8.jar:?] {}
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365) ~[mixin-patched-0.8.4.8.jar:?] {}
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-patched-0.8.4.8.jar:?] {}
	... 24 more
Caused by: java.lang.NullPointerException
	at java.util.ArrayDeque.addLast(ArrayDeque.java:303) ~[?:?] {re:computing_frames}
	at java.util.ArrayDeque.add(ArrayDeque.java:494) ~[?:?] {re:computing_frames}
	at dev.architectury.loom.forgeruntime.mixin.MixinIntermediaryDevRemapper.mapMethodName(MixinIntermediaryDevRemapper.java:135) ~[architectury-loom-runtime-1.1.3.jar:?] {}
	at org.spongepowered.asm.obfuscation.RemapperChain.mapMethodName(RemapperChain.java:59) ~[mixin-patched-0.8.4.8.jar:?] {}
	at org.spongepowered.asm.mixin.refmap.RemappingReferenceMapper.remapWithContext(RemappingReferenceMapper.java:595) ~[mixin-patched-0.8.4.8.jar:?] {}
	at org.spongepowered.asm.mixin.refmap.RemappingReferenceMapper.remap(RemappingReferenceMapper.java:567) ~[mixin-patched-0.8.4.8.jar:?] {}
	at org.spongepowered.asm.mixin.struct.AnnotatedMethodInfo.remap(AnnotatedMethodInfo.java:72) ~[mixin-patched-0.8.4.8.jar:?] {}
	at org.spongepowered.asm.mixin.injection.struct.MemberInfo.parse(MemberInfo.java:884) ~[mixin-patched-0.8.4.8.jar:?] {}
	at org.spongepowered.asm.mixin.injection.selectors.TargetSelector.parse(TargetSelector.java:408) ~[mixin-patched-0.8.4.8.jar:?] {}
	at org.spongepowered.asm.mixin.injection.selectors.TargetSelector.parse(TargetSelector.java:351) ~[mixin-patched-0.8.4.8.jar:?] {}
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parseSelectors(InjectionInfo.java:337) ~[mixin-patched-0.8.4.8.jar:?] {}
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:329) ~[mixin-patched-0.8.4.8.jar:?] {}
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316) ~[mixin-patched-0.8.4.8.jar:?] {}
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308) ~[mixin-patched-0.8.4.8.jar:?] {}
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46) ~[mixin-patched-0.8.4.8.jar:?] {}
	at jdk.internal.reflect.GeneratedConstructorAccessor24.newInstance(Unknown Source) ~[?:?] {re:classloading}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149) ~[mixin-patched-0.8.4.8.jar:?] {}
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708) ~[mixin-patched-0.8.4.8.jar:?] {}
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1311) ~[mixin-patched-0.8.4.8.jar:?] {}
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1042) ~[mixin-patched-0.8.4.8.jar:?] {}
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393) ~[mixin-patched-0.8.4.8.jar:?] {}
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[mixin-patched-0.8.4.8.jar:?] {}
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383) ~[mixin-patched-0.8.4.8.jar:?] {}
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365) ~[mixin-patched-0.8.4.8.jar:?] {}
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-patched-0.8.4.8.jar:?] {}
	... 24 more
```

**Comment by Juuxel** [comment]
Fixed by merging Fabric Loader's code into `MixinIntermediaryDevRemapper` (c0184af58c081aac377ff1a161279f01b4aaeb4d was probably the fix).
